import { useState, useCallback, useMemo } from 'react'
import { useParams, useNavigate } from 'react-router-dom'
import { useQuery } from '@tanstack/react-query'
import { fetchAircraft, aircraftImageUrl } from '../api/transport'
import type { OwnershipEntry } from '../api/transport'
import ImageLightbox from '../components/ImageLightbox'

function formatDate(d: string) {
  return new Date(d + 'T00:00:00').toLocaleDateString('en-GB', {
    day: 'numeric', month: 'short', year: 'numeric',
  })
}

function parseDate(d: string | null): Date | null {
  if (!d) return null
  // Handle both ISO "2021-09-26" and display "26-Sep-2021" formats
  if (/^\d{4}-\d{2}-\d{2}/.test(d)) return new Date(d)
  const parsed = Date.parse(d)
  return isNaN(parsed) ? null : new Date(parsed)
}

function isOwnerDuringFlight(entry: OwnershipEntry, flightDate: string): boolean {
  const flight = new Date(flightDate + 'T00:00:00')
  const from = parseDate(entry.from)
  const to = entry.to ? parseDate(entry.to) : null
  if (!from) return false
  if (flight < from) return false
  if (to && flight > to) return false
  return true
}

const CLASS_LABEL: Record<number, string> = { 1: 'Economy', 2: 'Business', 3: 'First' }

export default function AircraftDetail() {
  const { registration } = useParams<{ registration: string }>()
  const navigate = useNavigate()
  const [lightbox, setLightbox] = useState(false)
  const [imgFailed, setImgFailed] = useState(false)
  const handleImgError = useCallback(() => setImgFailed(true), [])

  const { data: aircraft, isLoading } = useQuery({
    queryKey: ['aircraft', registration],
    queryFn: () => fetchAircraft(registration!),
    enabled: !!registration,
  })

  // Collect all flight dates to check which owners overlap
  const flightDates = useMemo(() => {
    if (!aircraft) return [] as string[]
    return [
      ...aircraft.flights.map(f => f.date),
      ...aircraft.ga_flights.map(f => f.date),
    ]
  }, [aircraft])

  if (isLoading) {
    return (
      <div className="p-6 max-w-4xl">
        <div className="text-text-secondary text-sm">Loading aircraft details...</div>
      </div>
    )
  }

  if (!aircraft) {
    return (
      <div className="p-6 max-w-4xl">
        <div className="text-text-secondary">Aircraft not found</div>
      </div>
    )
  }

  return (
    <div className="p-6 max-w-4xl">
      {lightbox && (
        <ImageLightbox
          src={aircraftImageUrl(aircraft.registration, 'full')}
          alt={aircraft.registration}
          onClose={() => setLightbox(false)}
        />
      )}

      {/* Back */}
      <button
        onClick={() => navigate('/travel')}
        className="text-sm text-text-secondary hover:text-text-primary mb-4 inline-flex items-center gap-1"
      >
        &larr; Travel
      </button>

      {/* Header */}
      <div className="flex items-center gap-3 mb-6">
        <h2 className="text-xl font-bold text-text-primary">{aircraft.registration}</h2>
        {aircraft.aircraft_type && (
          <span className="px-2 py-0.5 text-xs rounded bg-bg-secondary text-text-secondary">
            {aircraft.aircraft_type}
          </span>
        )}
        {aircraft.register_url && (
          <a
            href={aircraft.register_url}
            target="_blank"
            rel="noopener noreferrer"
            className="text-xs text-text-secondary hover:text-accent"
          >
            Official register &rarr;
          </a>
        )}
      </div>

      {/* Aircraft photo */}
      {aircraft.has_aircraft_image && !imgFailed && (
        <div className="mb-6">
          <img
            src={aircraftImageUrl(aircraft.registration, 'full')}
            alt={aircraft.registration}
            className="rounded-lg max-h-96 cursor-pointer hover:opacity-90 transition-opacity"
            onError={handleImgError}
            onClick={() => setLightbox(true)}
          />
        </div>
      )}

      {/* Narrative */}
      {aircraft.narrative && (
        <div className="mb-6 bg-bg-card border border-border rounded-lg p-4">
          {aircraft.narrative.split('\n\n').map((para, i) => (
            <p key={i} className={`text-sm text-text-primary leading-relaxed ${i > 0 ? 'mt-3' : ''}`}>
              {para}
            </p>
          ))}
          <div className="mt-3 text-xs text-text-secondary">
            Generated by Claude
            {aircraft.narrative_generated_at && (
              <> &middot; {new Date(aircraft.narrative_generated_at).toLocaleDateString('en-GB', {
                day: 'numeric', month: 'short', year: 'numeric',
              })}</>
            )}
          </div>
        </div>
      )}

      {/* Ownership timeline */}
      {aircraft.ownership_timeline.length > 0 && (
        <div className="mb-6">
          <h3 className="text-sm font-semibold text-text-primary mb-2">Ownership history</h3>
          <div className="bg-bg-card border border-border rounded-lg overflow-hidden">
            {aircraft.ownership_timeline.map((entry, i) => {
              const youFlew = flightDates.some(d => isOwnerDuringFlight(entry, d))
              return (
                <div
                  key={i}
                  className={`px-4 py-3 border-b border-border last:border-0 ${
                    youFlew ? 'bg-accent/10 border-l-2 border-l-accent' : ''
                  }`}
                >
                  <div className="flex items-center gap-2">
                    <span className={`text-sm font-medium ${youFlew ? 'text-accent' : 'text-text-primary'}`}>
                      {entry.owner}
                    </span>
                    {youFlew && (
                      <span className="text-[10px] uppercase tracking-wider text-accent font-semibold">
                        You flew with this owner
                      </span>
                    )}
                  </div>
                  <div className="text-xs text-text-secondary mt-0.5">
                    {entry.from_display} &ndash; {entry.to_display}
                  </div>
                </div>
              )
            })}
          </div>
        </div>
      )}

      {/* Commercial flights */}
      {aircraft.flights.length > 0 && (
        <div className="mb-6">
          <h3 className="text-sm font-semibold text-text-primary mb-2">
            Your flights ({aircraft.flights.length})
          </h3>
          <div className="bg-bg-card border border-border rounded-lg overflow-hidden">
            <table className="w-full text-sm">
              <thead>
                <tr className="border-b border-border bg-bg-secondary">
                  <th className="text-left px-3 py-2 text-xs text-text-secondary font-medium">Date</th>
                  <th className="text-left px-3 py-2 text-xs text-text-secondary font-medium">Route</th>
                  <th className="text-left px-3 py-2 text-xs text-text-secondary font-medium">Flight</th>
                  <th className="text-left px-3 py-2 text-xs text-text-secondary font-medium">Airline</th>
                  <th className="text-left px-3 py-2 text-xs text-text-secondary font-medium">Class</th>
                  <th className="text-right px-3 py-2 text-xs text-text-secondary font-medium">Dist</th>
                </tr>
              </thead>
              <tbody>
                {aircraft.flights.map(f => (
                  <tr key={f.id} className="border-b border-border last:border-0 hover:bg-bg-hover">
                    <td className="px-3 py-2 text-text-secondary text-xs whitespace-nowrap">{formatDate(f.date)}</td>
                    <td className="px-3 py-2 font-medium text-text-primary">
                      {f.dep_airport} &rarr; {f.arr_airport}
                    </td>
                    <td className="px-3 py-2 text-text-secondary">{f.flight_number || '\u2014'}</td>
                    <td className="px-3 py-2 text-text-secondary">{f.airline || '\u2014'}</td>
                    <td className="px-3 py-2 text-text-secondary">
                      {f.flight_class ? CLASS_LABEL[f.flight_class] || '\u2014' : '\u2014'}
                    </td>
                    <td className="px-3 py-2 text-text-secondary text-right text-xs">
                      {f.distance_km ? `${f.distance_km.toLocaleString()} km` : ''}
                    </td>
                  </tr>
                ))}
              </tbody>
            </table>
          </div>
        </div>
      )}

      {/* GA flights */}
      {aircraft.ga_flights.length > 0 && (
        <div className="mb-6">
          <h3 className="text-sm font-semibold text-text-primary mb-2">
            Your GA flights ({aircraft.ga_flights.length})
          </h3>
          <div className="bg-bg-card border border-border rounded-lg overflow-hidden">
            <table className="w-full text-sm">
              <thead>
                <tr className="border-b border-border bg-bg-secondary">
                  <th className="text-left px-3 py-2 text-xs text-text-secondary font-medium">Date</th>
                  <th className="text-left px-3 py-2 text-xs text-text-secondary font-medium">Route</th>
                  <th className="text-left px-3 py-2 text-xs text-text-secondary font-medium">Captain</th>
                  <th className="text-left px-3 py-2 text-xs text-text-secondary font-medium">Exercise</th>
                  <th className="text-right px-3 py-2 text-xs text-text-secondary font-medium">Hours</th>
                </tr>
              </thead>
              <tbody>
                {aircraft.ga_flights.map(f => (
                  <tr key={f.id} className="border-b border-border last:border-0 hover:bg-bg-hover">
                    <td className="px-3 py-2 text-text-secondary text-xs whitespace-nowrap">{formatDate(f.date)}</td>
                    <td className="px-3 py-2 font-medium text-text-primary">
                      {f.dep_airport || '?'} &rarr; {f.arr_airport || '?'}
                    </td>
                    <td className="px-3 py-2 text-text-secondary">{f.captain || '\u2014'}</td>
                    <td className="px-3 py-2 text-text-secondary text-xs">{f.exercise || '\u2014'}</td>
                    <td className="px-3 py-2 text-text-secondary text-right">{f.hours_total ?? '\u2014'}</td>
                  </tr>
                ))}
              </tbody>
            </table>
          </div>
        </div>
      )}
    </div>
  )
}
